-- PolicyClaimHub - Oracle schema
-- Target: Oracle Autonomous Database / Oracle Database 19c+

CREATE TABLE insurance_policy (
    policy_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    policy_number      VARCHAR2(30 CHAR) NOT NULL,
    insured_name       VARCHAR2(150 CHAR) NOT NULL,
    sum_assured        NUMBER(18, 2) NOT NULL,
    premium_amount     NUMBER(18, 2) NOT NULL,
    coverage_start_date DATE NOT NULL,
    coverage_end_date   DATE NOT NULL,
    policy_status      VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_insurance_policy PRIMARY KEY (policy_id),
    CONSTRAINT uq_insurance_policy_number UNIQUE (policy_number),
    CONSTRAINT ck_policy_sum_assured CHECK (sum_assured > 0),
    CONSTRAINT ck_policy_premium CHECK (premium_amount > 0),
    CONSTRAINT ck_policy_dates CHECK (coverage_end_date > coverage_start_date),
    CONSTRAINT ck_policy_status CHECK (
        policy_status IN ('DRAFT', 'ACTIVE', 'EXPIRED', 'CANCELLED')
    )
);

CREATE TABLE motor_flood_claim (
    claim_id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    claim_number        VARCHAR2(30 CHAR) NOT NULL,
    policy_id           NUMBER NOT NULL,
    vehicle_registration VARCHAR2(20 CHAR) NOT NULL,
    incident_date       DATE NOT NULL,
    district            VARCHAR2(100 CHAR) NOT NULL,
    incident_location   MDSYS.SDO_GEOMETRY NOT NULL,
    water_depth_cm      NUMBER(8, 2) NOT NULL,
    requested_amount    NUMBER(18, 2) NOT NULL,
    deductible_amount   NUMBER(18, 2) DEFAULT 0 NOT NULL,
    outstanding_debt    NUMBER(18, 2) DEFAULT 0 NOT NULL,
    estimated_payout    NUMBER(18, 2) DEFAULT 0 NOT NULL,
    approved_amount     NUMBER(18, 2),
    claim_status        VARCHAR2(30 CHAR) DEFAULT 'SUBMITTED' NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_motor_flood_claim PRIMARY KEY (claim_id),
    CONSTRAINT uq_motor_flood_claim_number UNIQUE (claim_number),
    CONSTRAINT fk_claim_policy FOREIGN KEY (policy_id)
        REFERENCES insurance_policy (policy_id),
    CONSTRAINT ck_claim_water_depth CHECK (water_depth_cm BETWEEN 0 AND 500),
    CONSTRAINT ck_claim_requested CHECK (requested_amount > 0),
    CONSTRAINT ck_claim_deductible CHECK (deductible_amount >= 0),
    CONSTRAINT ck_claim_debt CHECK (outstanding_debt >= 0),
    CONSTRAINT ck_claim_status CHECK (
        claim_status IN (
            'DRAFT', 'SUBMITTED', 'UNDER_REVIEW',
            'NEED_MORE_INFO', 'APPROVED', 'REJECTED', 'PAID'
        )
    )
);

CREATE INDEX ix_claim_policy_id
    ON motor_flood_claim (policy_id);

CREATE INDEX ix_claim_district_date
    ON motor_flood_claim (district, incident_date);

CREATE TABLE claim_status_history (
    history_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    claim_id        NUMBER NOT NULL,
    previous_status VARCHAR2(30 CHAR),
    new_status      VARCHAR2(30 CHAR) NOT NULL,
    changed_by      VARCHAR2(100 CHAR) NOT NULL,
    change_note     VARCHAR2(500 CHAR),
    changed_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_claim_status_history PRIMARY KEY (history_id),
    CONSTRAINT fk_history_claim FOREIGN KEY (claim_id)
        REFERENCES motor_flood_claim (claim_id)
);

CREATE INDEX ix_claim_history_claim_id
    ON claim_status_history (claim_id, changed_at);

CREATE TABLE flood_area (
    flood_area_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    area_name     VARCHAR2(150 CHAR) NOT NULL,
    severity      VARCHAR2(20 CHAR) NOT NULL,
    observed_at   TIMESTAMP NOT NULL,
    area_geometry MDSYS.SDO_GEOMETRY NOT NULL,
    CONSTRAINT pk_flood_area PRIMARY KEY (flood_area_id),
    CONSTRAINT ck_flood_area_severity CHECK (
        severity IN ('LOW', 'MEDIUM', 'HIGH', 'SEVERE')
    )
);

DELETE FROM user_sdo_geom_metadata
WHERE table_name IN ('MOTOR_FLOOD_CLAIM', 'FLOOD_AREA');

INSERT INTO user_sdo_geom_metadata (
    table_name,
    column_name,
    diminfo,
    srid
)
VALUES (
    'MOTOR_FLOOD_CLAIM',
    'INCIDENT_LOCATION',
    MDSYS.SDO_DIM_ARRAY(
        MDSYS.SDO_DIM_ELEMENT('LONGITUDE', -180, 180, 0.005),
        MDSYS.SDO_DIM_ELEMENT('LATITUDE', -90, 90, 0.005)
    ),
    4326
);

INSERT INTO user_sdo_geom_metadata (
    table_name,
    column_name,
    diminfo,
    srid
)
VALUES (
    'FLOOD_AREA',
    'AREA_GEOMETRY',
    MDSYS.SDO_DIM_ARRAY(
        MDSYS.SDO_DIM_ELEMENT('LONGITUDE', -180, 180, 0.005),
        MDSYS.SDO_DIM_ELEMENT('LATITUDE', -90, 90, 0.005)
    ),
    4326
);

CREATE INDEX six_claim_incident_location
    ON motor_flood_claim (incident_location)
    INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

CREATE INDEX six_flood_area_geometry
    ON flood_area (area_geometry)
    INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

COMMIT;
